[package]
name = "sportgems"
version = "0.1.0"
authors = ["Fabian Gebhart <...>"]
edition = "2018"

[dependencies]
rayon = "1.0.2"
pyo3 = { path = "../..", features = ["extension-module"] }


[lib]
name = "sportgems"
crate-type = ["cdylib"]