[package]
name = "sportgems"
version = "0.1.0"
authors = ["Fabian Gebhart <...>"]

[dependencies]
pyo3 = { version="0.2.3", features=["extension-module"] }

[lib]
name = "sportgems"
crate-type = ["cdylib"]