[package]
name = "sportgems"
version = "0.1.0"
edition = "2018"
authors = ["Fabian Gebhart"]

[lib]
name = "sportgems"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.12.4"
features = ["extension-module"]