site_name: sportgems

repo_url: https://github.com/fgebhart/sportgems/
repo_name: fgebhart/sportgems
edit_uri: edit/master/docs
site_author: Fabian Gebhart
site_description: Library to find valuable gems in your activities.

theme:
  name: material
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

nav:
  - Getting Started: index.md
  - Module Reference: module_reference.md
  - Changelog: changelog.md

plugins:
- search:
    min_search_length: 2
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        setup_commands:
            - import sys, shutil
            - sys.path.remove("")
            - sys.path.insert(0, "docs")
            - shutil.copyfile('sportgems/__init__.pyi', 'docs/sportgems/__init__.py')
        selection:
          docstring_style: "google"
        rendering:
          show_root_heading: true
          show_source: false
          heading_level: 3

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
