name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: cargo build
      run: cargo build --verbose
      
    - name: cargo test
      run: cargo test --verbose
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install python dependencies for building
      run: python -m pip install --upgrade pip maturin wheel

    - name: Build python wheel
      run: maturin build
    
    - name: Install sportgems wheel
      run: |
        ls -l target/wheels/
        pip install target/wheels/sportgems-0.1.1-cp38-cp38-manylinux1_x86_64.whl

    - name: Test sportgems
      run: |
        pytest tests/ -v
