name: Build ARMv7

on: [push]

jobs:
  build_arm7:
    name: Build ARMv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install apt Packages
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          export DEBIAN_FRONTEND='noninteractive'
          sudo apt update && sudo apt install -y  gcc-arm-linux-gnueabihf \
                                        wget \
                                        make \
                                        vim \
                                        python3.8 \
                                        python3-pip \
                                        virtualenv \
                                        python3-dev \
                                        python3-setuptools \
                                        python3-wheel \
                                        virtualenv \
                                        python3-pip \
                                        git \
                                        cmake \
                                        libssl-dev \
                                        autoconf \
                                        automake \
                                        build-essential \
                                        zlib1g-dev \
                                        libbz2-dev \
                                        liblzma-dev \
                                        libncurses5-dev \
                                        libreadline6-dev \
                                        libsqlite3-dev \
                                        libgdbm-dev \
                                        lzma \
                                        lzma-dev \
                                        curl \
                                        g++ \
                                        unzip \
                                        sqlite3 \
                                        openssl \
                                        tcl8.6-dev \
                                        tk8.6-dev \
                                        libreadline-dev

      - name: Set up Virtual Environment and Install Maturin
        run: |
          virtualenv -p python3.8 venv
          source venv/bin/activate
          python --version
          pip install maturin

      - name: Download, Install and Configure Rust
        run: |
          wget https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
          chmod +x rustup-init
          printf '%s\n' 1 | ./rustup-init
          source $HOME/.cargo/env
          rustup default nightly
          rustc -V
          rustup target add armv7-unknown-linux-gnueabihf
          mkdir -p ~/.cargo
          echo '[target.armv7-unknown-linux-gnueabihf]
          linker = "arm-linux-gnueabihf-gcc"' > ~/.cargo/config

      - name: Download and Unpack Python
        run: |
          wget https://www.python.org/ftp/python/3.8.6/Python-3.8.6.tgz
          tar -xvzf Python-3.8.6.tgz

      - name: fix lsb_release issue
        run: |
          cat /usr/bin/lsb_release
          ls -l /usr/bin/python3.8
          sudo ln -s /usr/bin/python3 /usr/bin/python3.8
          ls -l /usr/bin/python3

      - name: Build Python for ARM
        run: |
          cd Python-3.8.6
          CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ AR=arm-linux-gnueabihf-ar \
              RANLIB=arm-linux-gnueabihf-ranlib \
              ./configure --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf \
              --build=x86_64-linux-gnu --prefix=$HOME/rapsberry/depsBuild/python \
              --disable-ipv6 ac_cv_file__dev_ptmx=no ac_cv_file__dev_ptc=no \
              ac_cv_have_long_long_format=yes --enable-shared

          make HOSTPYTHON=$HOME/raspberry/depsBuild/pythonhost/python \
              BLDSHARED="arm-linux-gnueabihf-gcc -shared" CROSS-COMPILE=arm-linux-gnueabihf- \
              CROSS_COMPILE_TARGET=yes HOSTARCH=arm-linux BUILDARCH=arm-linux-gnueabihf

          make altinstall HOSTPYTHON=$HOME/raspberry/depsBuild/pythonhost/python \
              BLDSHARED="arm-linux-gnueabihf-gcc -shared" CROSS-COMPILE=arm-linux-gnueabihf- \
              CROSS_COMPILE_TARGET=yes HOSTARCH=arm-linux BUILDARCH=arm-linux-gnueabihf \
              prefix=$HOME/Python-3.8-rpi/_install

      - name: Cross Compile
        run: |
          export PYO3_CROSS_INCLUDE_DIR="$HOME/Python-3.8-rpi/_install/include"
          export PYO3_CROSS_LIB_DIR="$HOME/Python-3.8-rpi/_install/lib"
          maturin build --target=armv7-unknown-linux-gnueabihf --manylinux=off --release

      - name: Verify Target is present
        run: |
          ls -l target/wheels
          ls -l target/sportgems-*-cp38-cp38-linux_armv7l.whl

