name: ARMv7 build

on: [push]

jobs:
  linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Python
        run: |
          cd /tmp
          wget https://www.python.org/ftp/python/3.8.6/Python-3.8.6.tgz
          tar -xvzf Python-3.8.6.tgz
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install apt packages
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update && sudo apt install gcc-arm-linux-gnueabihf
      - name: Build Python for ARM
        env:
          HOSTPYTHON: /tmp/depsBuild/pythonhost/python
          CONFIGURE_PREFIX: /tmp/python
          BUILT_ARM_PYTHON: /tmp/Python-3.8.6
        run: |
          cd $BUILT_ARM_PYTHON
          CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ AR=arm-linux-gnueabihf-ar \
            RANLIB=arm-linux-gnueabihf-ranlib \
            ./configure --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf \
            --build=x86_64-linux-gnu --prefix=$CONFIGURE_PREFIX \
            --disable-ipv6 ac_cv_file__dev_ptmx=no ac_cv_file__dev_ptc=no \
            ac_cv_have_long_long_format=yes --enable-shared

          make HOSTPYTHON=$HOSTPYTHON \
            BLDSHARED="arm-linux-gnueabihf-gcc -shared" CROSS-COMPILE=arm-linux-gnueabihf- \
            CROSS_COMPILE_TARGET=yes HOSTARCH=arm-linux BUILDARCH=arm-linux-gnueabihf

          make altinstall HOSTPYTHON=$HOSTPYTHON \
            BLDSHARED="arm-linux-gnueabihf-gcc -shared" CROSS-COMPILE=arm-linux-gnueabihf- \
            CROSS_COMPILE_TARGET=yes HOSTARCH=arm-linux BUILDARCH=arm-linux-gnueabihf \
            prefix=$BUILT_ARM_PYTHON

      - name: Build ARM wheel
        env:
          BUILT_ARM_PYTHON: /tmp/Python-3.8.6
        run: |
          PYO3_CROSS_INCLUDE_DIR="$BUILT_ARM_PYTHON/include" PYO3_CROSS_LIB_DIR="$BUILT_ARM_PYTHON/_install/lib" maturin build --target=armv7-unknown-linux-gnueabihf --release

      - name: Verify Target is present
        run: |
          ls -l target/sportgems-*-manylinux1_armv7l.whl
