name: Release Manylinux

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip maturin==0.9.4

      - name: Build & Publish to PyPi
        run: maturin publish --username ${{ secrets.PYPI_USERNAME }} --no-sdist --interpreter python${{matrix.python_version}} --manylinux=2014
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
