name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
    
    - name: Install dependencies & build
      run: |
        python -m pip install --upgrade pip maturin wheel
        maturin build

    - name: Install sportgems wheel
      run: pip install target/wheels/sportgems*.whl

    - name: Test sportgems
      run: |
        pytest tests/ -v
