name: Test

on:
  pull_request:
  workflow_dispatch:  # allow running tests via github ui button

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
      
    - name: Cargo build
      run: cargo build --verbose
      
    - name: Cargo test
      run: cargo test --verbose --no-default-features
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python dependencies for building
      run: python -m pip install --upgrade pip maturin==0.9.4 wheel

    - name: Build python wheel
      run: maturin build -i python${{ matrix.python-version }}
    
    - name: Install sportgems wheel
      run: |
        ls -l target/wheels/
        pip install target/wheels/sportgems-*-manylinux*_x86_64.whl

    - name: Install python dependencies for testing
      run: python -m pip install -r requirements.txt

    - name: Test sportgems
      run: |
        pytest tests/ -v --color=yes
